# Generated by Django 5.2.15 on 2026-06-30 20:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('pos', '0004_menuitem_price_today'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItemRecipe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=4, help_text='Cantidad consumida por plato', max_digits=10)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='inventory.inventoryitem')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='pos.menuitem')),
            ],
            options={
                'verbose_name': 'Receta de item',
                'verbose_name_plural': 'Recetas de items',
                'unique_together': {('menu_item', 'inventory_item')},
            },
        ),
    ]
