# Generated by Django 5.2.15 on 2026-06-30 20:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeShift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clock_in', models.DateTimeField(auto_now_add=True)),
                ('clock_out', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Turno de empleado',
                'verbose_name_plural': 'Turnos de empleados',
                'ordering': ['-clock_in'],
            },
        ),
    ]
