# Generated by Django 5.2.15 on 2026-06-30 20:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_employeeshift'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='employee_discount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Porcentaje de descuento para consumos personales (ej. 50.00 para 50%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='user',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Pago por hora trabajada', max_digits=10),
        ),
        migrations.CreateModel(
            name='EmployeePayout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('hours_worked', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('base_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tips_share', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('deductions', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('net_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pago de nómina',
                'verbose_name_plural': 'Pagos de nóminas',
                'ordering': ['-period_end'],
            },
        ),
    ]
