# Generated by Django 5.2.15 on 2026-06-30 20:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_employee_discount_user_hourly_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='employee_discount',
        ),
        migrations.AddField(
            model_name='user',
            name='commission_pct',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de comisión por ventas', max_digits=5),
        ),
        migrations.AlterField(
            model_name='user',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Sueldo base por hora', max_digits=10),
        ),
        migrations.CreateModel(
            name='PayrollPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('wages_earned', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('commissions_earned', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tips_earned', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('deductions', models.DecimalField(decimal_places=2, default=0, help_text='Deducción por consumo de empleado', max_digits=10)),
                ('net_pay', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagado')], default='pending', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pago de nómina',
                'verbose_name_plural': 'Pagos de nóminas',
                'ordering': ['-period_end'],
            },
        ),
        migrations.DeleteModel(
            name='EmployeePayout',
        ),
    ]
