# Generated by Django 5.2.15 on 2026-06-30 10:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NCFSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ncf_type', models.CharField(choices=[('B01', 'Factura de Consumo'), ('B04', 'Nota de Crédito'), ('B14', 'Gastos Menores')], max_length=3, unique=True)),
                ('prefix', models.CharField(default='A01', max_length=3)),
                ('current_sequence', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Secuencia NCF',
                'verbose_name_plural': 'Secuencias NCF',
            },
        ),
        migrations.AddField(
            model_name='ecfdocument',
            name='alanube_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ecfdocument',
            name='json_payload',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ecfdocument',
            name='ncf_type',
            field=models.CharField(choices=[('B01', 'Factura de Consumo'), ('B04', 'Nota de Crédito'), ('B14', 'Gastos Menores')], default='B01', max_length=3),
        ),
        migrations.AddField(
            model_name='ecfdocument',
            name='razon_social_cliente',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
