# Generated by Django 5.2.15 on 2026-06-30 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_ncfsequence_ecfdocument_alanube_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecfdocument',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('sent', 'Enviado'), ('accepted', 'Aceptado DGII'), ('rejected', 'Rechazado'), ('failed', 'Falló envío')], default='pending', max_length=10),
        ),
    ]
