# Generated by Django 5.2.15 on 2026-06-30 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_alter_ecfdocument_status'),
        ('pos', '0004_menuitem_price_today'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='pos.order'),
        ),
    ]
