# Generated by Django 5.2.15 on 2026-06-30 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_alter_payment_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='items_json',
            field=models.JSONField(blank=True, help_text='Detalle de ítems pagados', null=True),
        ),
    ]
