# Generated by Django 5.2.15 on 2026-06-30 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_payment_deduct_from_payroll_payment_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='deduct_from_payroll',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='employee',
        ),
    ]
