# Generated by Django 5.2.15 on 2026-06-30 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_remove_payment_deduct_from_payroll_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='deduct_from_payroll',
            field=models.BooleanField(default=False, help_text='Deducir de nómina'),
        ),
        migrations.AddField(
            model_name='payment',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_purchases', to=settings.AUTH_USER_MODEL),
        ),
    ]
