# Generated by Django 5.2.15 on 2026-06-30 10:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_table_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
