# Generated by Django 5.2.15 on 2026-06-30 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_alter_table_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='price_today',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio variable del día (mariscos). Si está vacío, se usa price.', max_digits=10, null=True),
        ),
    ]
